# Generated by Django 5.2 on 2025-06-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_user'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_date', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='reservationstatus',
            options={'verbose_name_plural': 'Reservation Statuses'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.reservationstatus'),
        ),
        migrations.AlterField(
            model_name='reservationstatus',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
